<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>School Loan</title>';
echo '<!--Google Font-->';
echo '<link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500&display=swap" rel="stylesheet">';
echo '<!--Stylesheet-->';
echo '<link rel="stylesheet" href="style.css">';
echo '<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>';
echo '</head>';
echo '<body>';
echo '<nav>';
echo '<div class="logo">';
echo '<img src="images/logo.jpeg" alt="Italian Trulli">';
echo '<p>Lyceum of the Philippines University</p>';
echo '</div>';
echo '<ul>';
echo '<li><a href="#"> HOME</a></li>';
echo '<li><a href="#"> About</a></li>';
echo '<li><a href="#"> Services</a></li>';
echo '<li><a href="#"> Contact Us</a>';
echo '</li>';
echo '';
echo '</ul>';
echo '</nav>';
echo '<div class="container">';
echo '<div class="head-title">';
echo '<h2>Tuition Calculator</h2>';
echo '</div>';
echo '<section>';
echo '<div class="wrapper">';
echo '<label for="no-of-units" class="lbl">';
echo 'Total No. of Units';
echo '</label>';
echo '<span id="split-num" class="val">';
echo '0';
echo '</span>';
echo '</div>';
echo '<input type="range" min="1" max="50" id="no-of-units" value="1">';
echo '<div class="wrapper">';
echo '<label for="lab" class="lbl">';
echo 'No. of Laboratory:';
echo '</label>';
echo '<span id="lab-percent" class="val">';
echo '0';
echo '</span>';
echo '</div>';
echo '<input type="range" min="1" id="lab" value="15">';
echo '</section>';
echo '<section>';
echo '<div class="wrapper">';
echo '<label for="amount" class="lbl">';
echo 'Amount per Unit:';
echo '</label>';
echo '<div class="input-box">';
echo '<span></span>';
echo '<input type="number" value="0" id="amount" class="val">';
echo '</div>';
echo '</div>';
echo '<div class="wrapper">';
echo '<span class="lbl">Laboratory Fee: </span>';
echo '<span id="lab-amount" class="val">';
echo '0';
echo '</span>';
echo '</div>';
echo '<hr>';
echo '<div class="wrapper">';
echo '<span class="lbl">Total Amount</span>';
echo '<span id="total-amount" class="val">';
echo '0';
echo '</span>';
echo '</div>';
echo '</section>';
echo '';
echo '<section>';
echo '<div class="wrapper">';
echo '<span class="lbl">';
echo 'Per laboratory Amount';
echo '</span>';
echo '<span id="amount-per-unit" class="val">';
echo '0';
echo '</span>';
echo '</div>';
echo '<div class="wrapper">';
echo '<span class="lbl">';
echo 'Total Amount';
echo '</span>';
echo '<span id="total-per-unit" class="val">';
echo '0';
echo '</span>';
echo '</div>';
echo '</section>';
echo '</div>';
echo '<div class="container-image">';
echo '<div class="image-container">';
echo '';
echo '</div>';
echo '</div>';
echo '<footer>';
echo '<ul class="footer-icons">';
echo '<li><a href=""><ion-icon name="logo-facebook"></ion-icon></a></li>';
echo '<li><a href=""><ion-icon name="logo-twitter"></ion-icon></a></li>';
echo '<li><a href=""><ion-icon name="logo-instagram"></ion-icon></a></li>';
echo '<li><a href=""><ion-icon name="mail-outline"></ion-icon></a></li>';
echo '</ul>';
echo '<ul class="footer-menu">';
echo '<li><a href="">Home</a></li>';
echo '<li><a href="">About</a></li>';
echo '<li><a href="">Services</a></li>';
echo '<li><a href="">Contact</a></li>';
echo '';
echo '<div class="footer-copyright">';
echo '<p>This is for educational purposes only. All Rights Reserved 2022 :: Created by Anthony Macariola</p>';
echo '</div>';
echo '';
echo '</ul>';
echo '</footer>';
echo '<script src="script.js"></script>';
echo '</body>';
echo '</html>';
?>